### ISSUE TITLE
Org support

### ISSUE THREAD

**Issue by fregante** [jgierer12/prettier-github#15]
It doesn't seem to work on repos that are not on my account. Is that a GHApps limit?

Example: https://github.com/GhostText/GhostText/issues/101

**Comment by jgierer12** [comment]
Hmm, it doesn't show up in my logs at all... Did you install the app to your org correctly?

**Comment by fregante** [comment]
Ah, it looks like I have to install it separately on the accounts/orgs I can administer:

<img width="537" alt="screen shot 2017-06-23 at 01 04 25" src="https://user-images.githubusercontent.com/1402241/27446428-1b850938-57b0-11e7-820f-26d4e9dbfee7.png">

I can't just install it once and select multiple. Also I can't install it on orgs that I'm a simple member of.
