### ISSUE TITLE
Add a comment to the updated code

### ISSUE THREAD

**Issue by k15a** [jgierer12/prettier-github#3]
I think it would be great if you add a comment to the markdown which says that the code got formatted with prettier.

Input:
````md
```js
// some code
```
````

Output:
````md
<!-- We formatted your code with prettier.
Change this comment to "prettier-github disable" to disable automatic code formatting.
Learn more at https://github.com/jgierer12/prettier-github -->
```js
// some formatted code
```
````

This way only the author of the comment can see the comment if they try to remove the formatting. Probably add the original code in the comment as well.

What do you think?

**Comment by jgierer12** [comment]
👍 great idea
