### ISSUE TITLE
Apply to all repos under one account

### ISSUE THREAD

**Issue by fregante** [jgierer12/prettier-github#6]
The instructions are for one repo at a time. Is it possible have it apply to all repos automatically?

**Comment by jgierer12** [comment]
Unfortunately not right now, since you need to add a webhook to every repo. However, we could explore adding the webhook programmatically after the bot is installed

**Comment by fregante** [comment]
Perhaps this can be done with an integration: https://github.com/blog/2226-build-an-integration-for-github

**Comment by jgierer12** [comment]
I'm thinking about that too, but it would involve me hosting it vs. users self-hosting. Not sure if I want to do that (yet)

**Comment by audiolion** [comment]
if you self-hosted there would be opportunity to make money, but it is a lot more to manage and might not be worth

**Comment by fregante** [comment]
Not necessarily, in the instructions for my bot I create my own integration: https://github.com/bfred-it/index-github-bot

**Comment by jgierer12** [comment]
> if you self-hosted there would be opportunity to make money

I don't plan to monetize this 😄 💸💸💸

> Not necessarily, in the instructions for my bot I create my own integration

👍 I'll look into that

**Comment by jgierer12** [comment]
I made Prettier GitHub a [GitHub app](https://github.com/apps/prettier-github) so you can now install it to all of your repos 🎉

**Comment by fregante** [comment]
Sweet! It even appears as edited by the app!

<img width="211" alt="edited by prettier-github" src="https://user-images.githubusercontent.com/1402241/27259839-aed2968e-544e-11e7-8588-c23076be1a51.png">
